#!/usr/bin/env python3
"""
Every brand asset, drawn from one definition of the Realhive mark.

The mark is six regular flat-topped hexagons around an empty centre, measured from the logo the
business supplied (frontend/web/branding/realhive-logo-source.jpeg). Drawing it as vectors rather
than cutting the JPEG gives clean transparent edges at every size, from a 16px favicon to a PDF
header, and a pure black version for thermal receipts.

    python3 scripts/brand/generate.py      (Pillow only)

Re-run after changing the mark or a colour; the outputs are committed.
"""

from __future__ import annotations

import base64
import math
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[2]

RED, GOLD, GREEN, BLACK = "#C81723", "#E0A226", "#0A763D", "#000000"

# Centres in the source image's 2048px space; every hexagon has a 210px circumradius.
RADIUS = 210
HEXAGONS = [
    ((1026, 622), RED),
    ((678, 824), BLACK),
    ((1374, 824), GOLD),
    ((678, 1228), RED),
    ((1374, 1228), GREEN),
    ((1026, 1428), BLACK),
]
# A square around the mark with a little air: the mark spans 468-1584 x 412-1610.
VIEW = (420, 410, 1212)  # x, y, size


def hexagon(cx: float, cy: float, r: float) -> list[tuple[float, float]]:
    return [(cx + r * math.cos(math.radians(a)), cy + r * math.sin(math.radians(a))) for a in range(0, 360, 60)]


def svg() -> str:
    x0, y0, size = VIEW
    shapes = "\n".join(
        f'  <polygon fill="{colour}" points="{" ".join(f"{x:.1f},{y:.1f}" for x, y in hexagon(cx, cy, RADIUS))}"/>'
        for (cx, cy), colour in HEXAGONS
    )
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{x0} {y0} {size} {size}" role="img" '
        f'aria-label="Realhive Group of Supermarkets">\n{shapes}\n</svg>\n'
    )


def raster(size: int, background: str | None = None, mono: bool = False, padding: float = 0.0) -> Image.Image:
    """The mark at {size}px square, drawn 4x larger and scaled down for smooth edges."""
    scale = 4
    big = size * scale
    image = Image.new("RGBA", (big, big), background or (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    x0, y0, view = VIEW
    inner = big * (1 - 2 * padding)
    factor = inner / view
    offset = big * padding
    for (cx, cy), colour in HEXAGONS:
        points = [((x - x0) * factor + offset, (y - y0) * factor + offset) for x, y in hexagon(cx, cy, RADIUS)]
        draw.polygon(points, fill=BLACK if mono else colour)
    return image.resize((size, size), Image.LANCZOS)


def receipt_logo(width: int = 192) -> str:
    """A 1-bit bitmap for ESC/POS raster printing (GS v 0), as a TypeScript module."""
    image = raster(width, background="#FFFFFF", mono=True).convert("L")
    bits = image.point(lambda value: 0 if value < 128 else 255, "1")
    width_bytes = (width + 7) // 8
    data = bytearray()
    for y in range(bits.height):
        for byte in range(width_bytes):
            value = 0
            for bit in range(8):
                x = byte * 8 + bit
                if x < width and bits.getpixel((x, y)) == 0:
                    value |= 0x80 >> bit
            data.append(value)
    encoded = base64.b64encode(bytes(data)).decode()
    return (
        "/**\n"
        " * The Realhive mark in black and white for thermal receipts: a raster for ESC/POS `GS v 0`,\n"
        " * one bit per dot, rows top to bottom. Generated by scripts/brand/generate.py - do not edit.\n"
        " */\n"
        f"export const RECEIPT_LOGO = {{\n  widthBytes: {width_bytes},\n  height: {bits.height},\n"
        f'  data: "{encoded}",\n}} as const;\n'
    )


def main() -> None:
    web = ROOT / "frontend/web"
    public = web / "public/brand"
    public.mkdir(parents=True, exist_ok=True)
    (public / "realhive-logo.svg").write_text(svg())
    for size in (192, 512):
        raster(size, padding=0.06).save(public / f"realhive-logo-{size}.png", optimize=True)
    # A maskable icon keeps its artwork inside the safe centre circle, on a solid background.
    raster(512, background="#FFFFFF", padding=0.18).convert("RGB").save(public / "realhive-maskable-512.png", optimize=True)

    app = web / "src/app"
    (app / "icon.svg").write_text(svg())
    raster(180, background="#FFFFFF", padding=0.1).convert("RGB").save(app / "apple-icon.png", optimize=True)
    icon = raster(256)
    icon.save(app / "favicon.ico", sizes=[(16, 16), (32, 32), (48, 48), (64, 64)])

    (web / "src/lib/lane/receipt-logo.ts").write_text(receipt_logo())

    # Email and PDF: on white, so the black hexagons survive a dark-mode mail client.
    for service, size in (("notification-service", 96), ("reporting-service", 256)):
        target = ROOT / f"backend/{service}/src/main/resources/brand"
        target.mkdir(parents=True, exist_ok=True)
        raster(size, background="#FFFFFF", padding=0.04).convert("RGB").save(target / "logo.png", optimize=True)

    print("Brand assets written.")


if __name__ == "__main__":
    main()
