import "server-only";

/**
 * Server configuration, read once and validated.
 *
 * Only the BFF talks to the gateway, so its address is a server secret of sorts: nothing here is
 * exposed to the browser (no NEXT_PUBLIC_ variables).
 */
function required(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`${name} is not set. Run \`make env\` or see .env.example.`);
  }
  return value;
}

export const serverEnv = {
  /** Where the BFF reaches the API gateway. */
  gatewayUrl: (process.env.GATEWAY_URL ?? "http://localhost:8080").replace(/\/$/, ""),
  /**
   * Encrypts the session cookies. At least 32 characters; generated by `make env`. Read lazily so
   * that `next build` does not need it.
   */
  get sessionSecret(): string {
    const secret = required("WEB_SESSION_SECRET");
    if (secret.length < 32) {
      throw new Error("WEB_SESSION_SECRET must be at least 32 characters.");
    }
    return secret;
  },
  /**
   * Browsers treat http://localhost as a secure context, so Secure cookies work in development.
   * Turn this off only to reach the app over plain HTTP from another host.
   */
  cookieSecure: process.env.WEB_COOKIE_SECURE !== "false",
  /** How many digits auth-service puts in an OTP. */
  otpLength: Number(process.env.OTP_LENGTH ?? 6),
};
